---
# ===== Update & Packages =====
- name: Update apt cache (Ubuntu)
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  tags:
    - base
    - packages

- name: Upgrade packages (safe)
  ansible.builtin.apt:
    upgrade: safe
  tags:
    - base
    - packages

- name: Install base packages
  ansible.builtin.apt:
    name: "{{ base_packages }}"
    state: present
  tags:
    - base
    - packages

# ===== Time & Timezone =====
- name: Detect container environment
  ansible.builtin.set_fact:
    base_is_container: "{{ (ansible_virtualization_type | default('')) in ['docker', 'container', 'lxc'] }}"
  tags:
    - base
    - time

# Containers: link /etc/localtime and write /etc/timezone
- name: "Containers | link /etc/localtime"
  ansible.builtin.file:
    src: "/usr/share/zoneinfo/{{ base_timezone }}"
    dest: /etc/localtime
    state: link
    force: true
  when: base_is_container | bool
  tags:
    - base
    - time

- name: "Containers | write /etc/timezone (Debian-like)"
  ansible.builtin.copy:
    dest: /etc/timezone
    content: "{{ base_timezone }}\n"
    owner: root
    group: root
    mode: "0644"
  when:
    - base_is_container | bool
    - ansible_os_family == "Debian"
  tags:
    - base
    - time

# Non-containers: install util-linux & set timezone
- name: "Non-containers | ensure util-linux (hwclock)"
  ansible.builtin.apt:
    name: util-linux
    state: present
    update_cache: true
  when:
    - not base_is_container | bool
    - ansible_os_family == "Debian"
  tags:
    - base
    - time

- name: "Non-containers | set timezone"
  community.general.timezone:
    name: "{{ base_timezone }}"
    hwclock: UTC
  when: not base_is_container | bool
  tags:
    - base
    - time

- name: Ensure timesyncd enabled
  ansible.builtin.systemd:
    name: systemd-timesyncd
    enabled: true
    state: started
  when:
    - ansible_service_mgr == "systemd"
    - not base_is_container | bool
  tags:
    - base
    - time
    - systemd

# ===== Swap (skip in containers) =====
- name: Disable swap (runtime)
  ansible.builtin.command: swapoff -a
  when:
    - not base_is_container | bool
    - (ansible_swaptotal_mb | default(0) | int) > 0
  changed_when: false
  tags:
    - k8s
    - swap

- name: Remove /swap.img from fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '^\s*/swap\.img\s+none\s+swap\s+sw\s+0\s+0\s*$'
    state: absent
    backup: true
  when: not base_is_container | bool
  tags:
    - k8s
    - swap

- name: Delete /swap.img
  ansible.builtin.file:
    path: /swap.img
    state: absent
  when: not base_is_container | bool
  tags:
    - k8s
    - swap

# ===== Kernel modules (skip in containers) =====
- name: Ensure br_netfilter loaded
  community.general.modprobe:
    name: br_netfilter
    state: present
  when: not base_is_container | bool
  tags:
    - base
    - k8s
    - kernel

- name: Ensure overlay loaded
  community.general.modprobe:
    name: overlay
    state: present
  when: not base_is_container | bool
  tags:
    - base
    - k8s
    - kernel


- name: Persist kernel modules
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      br_netfilter
      overlay
    owner: root
    group: root
    mode: '0644'
  notify: Reload modules
  when: not base_is_container | bool
  tags:
    - base
    - k8s
    - kernel

# ===== Sysctl (safe in containers) =====
- name: Apply Kubernetes sysctl params
  ansible.builtin.copy:
    dest: /etc/sysctl.d/99-k8s.conf
    content: |
      {% for k, v in base_k8s_sysctl.items() -%}
      {{ k }} = {{ v }}
      {% endfor -%}
    owner: root
    group: root
    mode: '0644'
  notify: Reload sysctl
  tags:
    - base
    - k8s
    - sysctl

# ===== SSH service (skip in containers) =====
- name: Ensure SSH service enabled
  ansible.builtin.systemd:
    name: ssh
    enabled: true
    state: started
  when:
    - ansible_service_mgr == "systemd"
    - not base_is_container | bool
  tags:
    - base
    - ssh
    - systemd

# ===== GitOps root =====
- name: Create GitOps root
  ansible.builtin.file:
    path: "{{ base_gitops_root }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags:
    - base
    - gitops

# ===== Firewall (skip in containers) =====
- name: Install UFW
  ansible.builtin.apt:
    name: ufw
    state: present
  when:
    - base_manage_ufw | bool
    - not base_is_container | bool
  tags:
    - base
    - firewall

- name: Allow SSH on UFW
  community.general.ufw:
    rule: allow
    name: OpenSSH
  when:
    - base_manage_ufw | bool
    - not base_is_container | bool
  tags:
    - base
    - firewall

- name: Enable UFW
  community.general.ufw:
    state: enabled
    logging: 'on'
  when:
    - base_manage_ufw | bool
    - not base_is_container | bool
  tags:
    - base
    - firewall

# ===== Controller public key (agent-based, optional) =====
- name: Read public keys from ssh-agent (localhost)
  when: base_manage_authorized_key | bool
  run_once: true
  delegate_to: localhost
  become: false
  vars:
    _agent_cmd: "ssh-add -L | awk 'NF'"
  set_fact:
    base_controller_pubkeys: "{{ lookup('pipe', _agent_cmd) | default('', true) }}"
  tags:
    - base
    - ssh

- name: Pick first public key from agent
  when: base_manage_authorized_key | bool
  run_once: true
  delegate_to: localhost
  become: false
  set_fact:
    base_controller_pubkey: "{{ (base_controller_pubkeys.splitlines() | first) | default('', true) }}"
  tags:
    - base
    - ssh

- name: Ensure ansible user SSH public key is present
  when:
    - base_manage_authorized_key | bool
    - not base_is_container | bool
  ansible.posix.authorized_key:
    user: ansible
    state: present
    key: "{{ base_controller_pubkey }}"
  tags:
    - base
    - ssh

- name: Disable SSH password authentication (production-like)
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
  notify: Restart SSH service
  when:
    - ansible_service_mgr == "systemd"
    - not base_is_container | bool
  tags:
    - base
    - ssh
    - systemd
