all:
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: "{{ lookup('env','HOME') }}/.ssh/id_ed25519"
    ansible_become: true
    ansible_python_interpreter: /usr/bin/python3
    cluster_name: "homelab"

  children:
    k3s_server:
      hosts:
        cp01-homelab:
          ansible_host: 192.168.100.18
    k3s_workers:
      hosts:
        wk01-homelab:
          ansible_host: 192.168.100.20
