---
- name: Check if old k3s-agent unit contains invalid flag (--flannel-backend)
  ansible.builtin.command: >
    grep -q -- '--flannel-backend' /etc/systemd/system/k3s-agent.service
  register: k3s_agent_flag_check
  changed_when: false
  failed_when: false

- name: Uninstall old k3s-agent with invalid flag
  ansible.builtin.command: /usr/local/bin/k3s-agent-uninstall.sh
  when: k3s_agent_flag_check.rc == 0
  args:
    removes: /etc/systemd/system/k3s-agent.service

- name: Download K3s installer script (agent)
  ansible.builtin.get_url:
    url: "{{ k3s_install_script_url }}"
    dest: "{{ k3s_install_script_path }}"
    mode: "0755"

- name: Install K3s agent (join to server)
  ansible.builtin.command: >
    sh {{ k3s_install_script_path }}
  environment:
    INSTALL_K3S_VERSION: "{{ k3s_channel_version }}"
    K3S_URL: "{{ k3s_server_url }}"
    K3S_TOKEN: "{{ vault_k3s_token }}"
  args:
    creates: /usr/local/bin/k3s-agent

- name: Ensure K3s agent service is enabled and running
  ansible.builtin.systemd:
    name: k3s-agent
    enabled: true
    state: started
