---
# Ensure the API is reachable before trying to join
- name: Wait for TCP 6443 on control-plane from workers
  ansible.builtin.wait_for:
    host: "{{ k3s_server_ip }}"
    port: 6443
    timeout: 60
  when: "'k3s_workers' in group_names"
  changed_when: false
  tags: [k3s]

# Detect legacy/invalid flag in existing unit (created by a previous run)
- name: Check if k3s-agent service file contains invalid flag
  ansible.builtin.command:
    cmd: grep -q -- '--flannel-backend' /etc/systemd/system/k3s-agent.service
  register: k3s_agent_flag_check
  failed_when: false
  changed_when: false
  when: "'k3s_workers' in group_names"
  tags: [k3s]

# Cleanly uninstall the old agent if the invalid flag is present
- name: Uninstall old k3s-agent with invalid flag
  ansible.builtin.command:
    cmd: /usr/local/bin/k3s-agent-uninstall.sh
  when:
    - "'k3s_workers' in group_names"
    - k3s_agent_flag_check.rc == 0
  changed_when: true
  tags: [k3s]

# Make sure systemd state is fresh after uninstall
- name: Daemon-reload after potential uninstall
  ansible.builtin.systemd:
    daemon_reload: true
  when: "'k3s_workers' in group_names"
  changed_when: false
  tags: [k3s]

# Download the official installer
- name: Download K3s installer script (agent)
  ansible.builtin.get_url:
    url: "{{ k3s_install_script_url }}"
    dest: "{{ k3s_install_script_path }}"
    mode: "0755"
  when: "'k3s_workers' in group_names"
  tags: [k3s]

# Install the agent WITHOUT any flannel flags
- name: Install K3s agent (join to server)
  ansible.builtin.command: >
    sh {{ k3s_install_script_path }}
  environment:
    INSTALL_K3S_VERSION: "{{ k3s_channel_version }}"
    INSTALL_K3S_SKIP_ENABLE: "false"
    K3S_URL: "{{ k3s_server_url }}"
    K3S_TOKEN: "{{ vault_k3s_token }}"
    INSTALL_K3S_EXEC: agent
  args:
    creates: /etc/systemd/system/k3s-agent.service
  when: "'k3s_workers' in group_names"
  tags: [k3s]

- name: Ensure K3s agent service is enabled and running
  ansible.builtin.systemd:
    name: k3s-agent
    enabled: true
    state: started
  when: "'k3s_workers' in group_names"
  tags: [k3s]
