---
galaxy_info:
  namespace: cchacon_dev
  role_name: base
  author: cchacon_dev
  description: Base role for homelab nodes
  license: MIT
  min_ansible_version: "2.15"

  platforms:
    - name: Ubuntu
      versions: [focal]
    - name: Debian
      versions: [bullseye, bookworm]

  galaxy_tags:
    - homelab
    - ubuntu
    - linux
    - ssh
    - users
    - timezone
    - hardening

dependencies: []
