---
- name: Base config on all nodes
  hosts: all
  become: true
  roles:
    - role: base
      tags:
        - base
        - packages
        - time
        - k8s
        - ssh
        - gitops
        - firewall
    - role: k3s
      tags:
        - k3s

- name: Install Cilium (CNI)
  hosts: k3s_server
  become: true
  gather_facts: false
  roles:
    - role: cilium
      tags:
        - cilium

- name: Install FluxCD (GitOps)
  hosts: k3s_server
  become: true
  gather_facts: false
  roles:
    - role: gitops
      tags: [gitops]
