---
- name: Converge base role
  hosts: all
  gather_facts: false        # <— clave
  become: false
  vars:
    ansible_remote_tmp: /var/tmp

  pre_tasks:
    - name: "Ensure /var/tmp is present and writable (raw)"
      ansible.builtin.raw: "mkdir -p /var/tmp && chmod 1777 /var/tmp"
      changed_when: false

    - name: "Gather facts now"
      ansible.builtin.setup:

    - name: Ensure tzdata present on Debian/Ubuntu
      ansible.builtin.apt:
        name: tzdata
        state: present
        update_cache: true
        cache_valid_time: 3600
      environment:
        DEBIAN_FRONTEND: noninteractive
        TZ: Etc/UTC
      when: ansible_os_family == "Debian"

    - name: Ensure base utilities on Debian/Ubuntu
      ansible.builtin.apt:
        name:
          - sudo
          - ca-certificates
          - openssh-client
        state: present
        update_cache: true
        cache_valid_time: 3600
      environment:
        DEBIAN_FRONTEND: noninteractive
      when: ansible_os_family == "Debian"

    - name: Ensure ansible user exists in containers
      ansible.builtin.user:
        name: ansible
        shell: /bin/bash
        create_home: true
      when: (ansible_virtualization_type | default('')) in ['docker', 'container', 'lxc']

    - name: Seed authorized_keys in containers
      ansible.posix.authorized_key:
        user: ansible
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAITestKeyForMolecule ansible@molecule"
        state: present
        manage_dir: true
      when: (ansible_virtualization_type | default('')) in ['docker', 'container', 'lxc']

  roles:
    - role: base
      vars:
        base_timezone: Etc/UTC
        base_manage_authorized_key: false
