---
driver:
  name: docker

platforms:
  - name: instance
    image: "geerlingguy/docker-ubuntu2204-ansible:latest"
    pre_build_image: true
    pull: true
    privileged: true

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/.."
  options:
    skip-tags: systemd
  playbooks:
    converge: converge.yml

dependency:
  name: galaxy
  options:
    requirements-file: collections.yml

lint: |
  set -e
  yamllint .
  ansible-lint
