---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: collections.yml

driver:
  name: docker

platforms:
  - name: instance-ubuntu
    image: "geerlingguy/docker-ubuntu2404-ansible:latest"
    pre_build_image: true
    command: sleep infinity
    privileged: false
    tty: true
    tmpfs:
      - /tmp
    env:
      ANSIBLE_DEPRECATION_WARNINGS: "false"

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    verify: verify.yml
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/.."
    ANSIBLE_REMOTE_TMP: "/var/tmp"
    ANSIBLE_LOCAL_TEMP: "/tmp"
  inventory:
    host_vars:
      instance-ubuntu:
        ansible_user: root
        ansible_python_interpreter: /usr/bin/python3
        ansible_remote_tmp: /var/tmp

verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
