---
ansible_user: ansible
ansible_port: 22
ansible_become: true
ansible_become_method: sudo
ansible_become_password: "{{ vault_become_password }}"
base_manage_authorized_key: true
base_timezone: "America/Costa_Rica"
base_gitops_root: "/srv/gitops"
ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"

k3s_cluster_cidr: "10.42.0.0/16"
k3s_service_cidr: "10.43.0.0/16"

k3s_version: "v1.33.5+k3s1"
cilium_version: "1.18.2"

k3s_api_host: "{{ hostvars['cp01-homelab']['ansible_host'] }}"
k3s_api_port: 6443
k3s_server_url: "https://{{ k3s_api_host }}:{{ k3s_api_port }}"

base_packages:
  - tzdata
  - ca-certificates
  - curl
  - git
  - htop
  - tmux
  - vim
  - unzip
  - gnupg
  - jq

base_k8s_sysctl:
  net.bridge.bridge-nf-call-iptables: 1
  net.bridge.bridge-nf-call-ip6tables: 1
  net.ipv4.ip_forward: 1
  net.ipv4.conf.all.rp_filter: 0
  net.ipv4.conf.default.rp_filter: 0

base_enable_unattended_upgrades: false
base_manage_ufw: false

k3s_install_script_url: "https://get.k3s.io"
k3s_install_script_path: "/usr/local/bin/install-k3s.sh"

k3s_channel_version: "{{ k3s_version }}"

gitops_flux_version: "v2.7.2"
gitops_release_base: "https://github.com/fluxcd/flux2/releases/download"
gitops_namespace: "flux-system"

gitops_kubeconfig_remote: "/etc/rancher/k3s/k3s.yaml"
gitops_kubeconfig_local: "/tmp/k3s_cp01_kubeconfig.yaml"

gitops_repo_url: "https://github.com/cchacon-dev/homelab-gitops.git"
gitops_repo_branch: "main"
gitops_repo_cluster_path: "clusters/homelab"

gitops_auth_method: "github_app"
gitops_github_app_id: "{{ gitops_github_app_id }}"
gitops_github_installation_id: "{{ gitops_github_installation_id }}"
gitops_github_app_private_key: "{{ gitops_github_app_private_key }}"

gitops_controllers:
  - source-controller
  - kustomize-controller
  - helm-controller
  - notification-controller
