---
ansible_user: ansible
ansible_ssh_private_key_file: ~/.ssh/id_ed25519
ansible_port: 22
ansible_become: true
ansible_become_method: sudo
ansible_become_password: "{{ vault_become_password }}"
base_manage_authorized_key: true
base_timezone: "America/Costa_Rica"
base_gitops_root: "/srv/gitops"

base_packages:
  - tzdata
  - ca-certificates
  - curl
  - git
  - htop
  - tmux
  - vim
  - unzip
  - gnupg
  - jq

base_k8s_sysctl:
  net.bridge.bridge-nf-call-iptables: 1
  net.bridge.bridge-nf-call-ip6tables: 1
  net.ipv4.ip_forward: 1

base_enable_unattended_upgrades: false
base_manage_ufw: false
