---
name: Lint

"on":
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install "ansible>=10" ansible-lint yamllint pre-commit

      - name: Install Ansible Galaxy collections
        run: |
          ansible-galaxy collection install -r collections/requirements.yml -p ~/.ansible/collections
        env:
          ANSIBLE_COLLECTIONS_PATH: ~/.ansible/collections

      - name: Write Ansible Vault password
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        run: |
          mkdir -p ~/.ansible
          printf "%s" "$ANSIBLE_VAULT_PASSWORD" > ~/.ansible/vault_pass.txt
          chmod 600 ~/.ansible/vault_pass.txt
          echo "ANSIBLE_VAULT_PASSWORD_FILE=$HOME/.ansible/vault_pass.txt" >> $GITHUB_ENV

      - name: Run pre-commit (all linters)
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
