---
name: Molecule

"on":
  pull_request:
  push:
    branches: [main]

jobs:
  molecule:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      ANSIBLE_CONFIG: ${{ github.workspace }}/ansible.cfg
      ANSIBLE_STDOUT_CALLBACK: yaml
      ANSIBLE_VERBOSITY: "3"
      ANSIBLE_COLLECTIONS_PATH: ~/.ansible/collections
      DOCKER_HOST: unix:///var/run/docker.sock

    strategy:
      fail-fast: false
      matrix:
        role:
          - ansible/roles/base

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install "ansible>=10" molecule "molecule-plugins[docker]" ansible-lint yamllint docker

      - name: Install Ansible Galaxy collections
        run: |
          ansible-galaxy collection install -r collections/requirements.yml -p ~/.ansible/collections
          ansible-galaxy collection install community.docker

      - name: Write Ansible Vault password
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        run: |
          mkdir -p ~/.ansible
          printf "%s" "$ANSIBLE_VAULT_PASSWORD" > ~/.ansible/vault_pass.txt
          chmod 600 ~/.ansible/vault_pass.txt
          echo "ANSIBLE_VAULT_PASSWORD_FILE=$HOME/.ansible/vault_pass.txt" >> $GITHUB_ENV

      - name: Docker sanity
        run: |
          docker version
          docker info

      - name: Molecule pre-destroy
        working-directory: ${{ matrix.role }}
        run: |
          molecule --debug destroy || true

      - name: Run Molecule tests
        working-directory: ${{ matrix.role }}
        run: |
          molecule --debug test -- \
            --skip-tags systemd,ssh_hardening \
            -e ansible_user=root \
            -e ansible_become_password= \
            -e ansible_python_interpreter=/usr/bin/python3
