---
name: Molecule

"on":
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies (Ansible + Molecule + Docker driver)
        run: |
          python -m pip install --upgrade pip
          pip install \
            "ansible>=10" \
            "molecule>=24.6.0" \
            "molecule-plugins[docker]>=23.5.0" \
            "pytest>=7" \
            "docker>=7"

      - name: Sanity check Docker
        run: |
          docker --version
          docker info | grep -E 'Server Version|Storage Driver'

      - name: Install galaxy collections
        run: |
          ansible-galaxy collection install -r collections/requirements.yml -p ~/.ansible/collections
        env:
          ANSIBLE_COLLECTIONS_PATH: ~/.ansible/collections

      - name: Run Molecule tests for base role
        working-directory: ansible/roles/base
        env:
          ANSIBLE_FORCE_COLOR: "1"
          PY_COLORS: "1"
        run: molecule test -s default
