---
name: Molecule

"on":
  push:
    paths:
      - "ansible/roles/base/**"
      - ".github/workflows/molecule.yml"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-3.12
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install "ansible-core>=2.16,<2.17" ansible-lint yamllint docker
          pip install "molecule>=24.6" "molecule-plugins[docker]>=23.5"

      - name: Cache Ansible Galaxy collections
        uses: actions/cache@v4
        with:
          path: ~/.ansible/collections
          key: galaxy-${{ runner.os }}-${{ hashFiles('ansible/roles/base/molecule/default/collections.yml') }}
          restore-keys: |
            galaxy-${{ runner.os }}-

      - name: Install Galaxy deps
        working-directory: ansible/roles/base/molecule/default
        run: |
          ansible-galaxy collection install -r collections.yml
          ansible-galaxy role install -r requirements.yml || true

      - name: Lint
        working-directory: ansible/roles/base
        run: |
          ansible-lint
          yamllint .

      - name: Molecule test
        working-directory: ansible/roles/base
        env:
          ANSIBLE_FORCE_COLOR: "1"
        run: |
          molecule --debug test -vvv
