---
name: Molecule

"on":
  pull_request:
  push:
    branches: [main]

jobs:
  molecule:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        role:
          - ansible/roles/base
          # - ansible/roles/common
          # - ansible/roles/docker

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install "ansible>=10" molecule "molecule-plugins[docker]" ansible-lint yamllint

      - name: Install Ansible Galaxy collections
        run: |
          ansible-galaxy collection install -r collections/requirements.yml -p ~/.ansible/collections
        env:
          ANSIBLE_COLLECTIONS_PATH: ~/.ansible/collections

      - name: Write Ansible Vault password
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        run: |
          mkdir -p ~/.ansible
          printf "%s" "$ANSIBLE_VAULT_PASSWORD" > ~/.ansible/vault_pass.txt
          chmod 600 ~/.ansible/vault_pass.txt
          echo "ANSIBLE_VAULT_PASSWORD_FILE=$HOME/.ansible/vault_pass.txt" >> $GITHUB_ENV

      - name: Run Molecule tests
        working-directory: ${{ matrix.role }}
        env:
          ANSIBLE_COLLECTIONS_PATH: ~/.ansible/collections
        run: |
          molecule test
