---
name: Molecule

"on":
  push:
    paths:
      - "ansible/roles/base/**"
      - "collections/requirements.yml"
      - ".github/workflows/molecule.yml"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-3.12
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install "ansible-core>=2.16,<2.17" ansible-lint yamllint docker
          pip install "molecule>=24.6" "molecule-plugins[docker]>=23.5"

      - name: Cache Ansible Galaxy collections
        uses: actions/cache@v4
        with:
          path: ~/.ansible/collections
          key: galaxy-${{ runner.os }}-${{ hashFiles('collections/requirements.yml') }}
          restore-keys: |
            galaxy-${{ runner.os }}-

      - name: Install Ansible collections (repo-wide)
        env:
          ANSIBLE_COLLECTIONS_PATH: ~/.ansible/collections:/usr/share/ansible/collections
        run: |
          ansible-galaxy collection install -r collections/requirements.yml -p ~/.ansible/collections

      - name: Install Galaxy roles (scenario-only)
        working-directory: ansible/roles/base/molecule/default
        run: |
          ansible-galaxy role install -r requirements.yml || true

      - name: Lint
        working-directory: ansible/roles/base
        run: |
          ansible-lint
          yamllint .

      - name: Molecule test
        working-directory: ansible/roles/base
        env:
          ANSIBLE_FORCE_COLOR: "1"
          ANSIBLE_COLLECTIONS_PATH: ~/.ansible/collections:/usr/share/ansible/collections
          MOLECULE_DEBUG: "1"
          ANSIBLE_VERBOSITY: "3"
        run: |
          molecule test
